image:
  repository: "hive-metastore-pgsql"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.3"

databaseSecret:
  create: true

postgres:
  host: 192.168.1.101
  port: 5432
  db: metastore
  username: postgres
  password: Sa12345678